### PR TITLE
jQuery Compatibility

### PR DESCRIPTION
**Pull request by bradlis7**
Adding jQuery compatibility layer as an optional javascript module.
#1

### CODE REVIEW

**Comment by otaq** [comment]
Looks good to me. Does it works as you expect?

**Comment by bradlis7** [comment]
I think so. I'm fairly new to ruby/rails.

Do we need to have a js dependency on `sortable-rails` inside `sortable-rails-jquery` so that they will always be added in order? This might be beneficial so that a person doesn't have to specify both, but can just do `sortable-rails-jquery`, right?

**Comment by otaq** [comment]
That's a good idea. So it's like this right?

```
# ../sortable-rails-jquery/index.js
//=require ../sortable-rails/Sortable.js
//=require ./jquery.binding.js
```

You can install gem locally by point gem path to folder in `Gemfile` for test.

```
gem "sortable-rails", path: "path/to/sortable-rails"
```

You can use `git rebase` or `git reset` to implement js dependency without add extra commit.

**Comment by bradlis7** [comment]
Works pretty well. I didn't document it, though.

I didn't understand what you meant by the last sentence. Did you want me to fix it so that there's only 1 commit in my pull request?

**Comment by otaq** [comment]
What I mean is this bf722e59d872ed27735f854df314b06693a0d3d2 can be done in 1d21dcc06c40a12ed1c7859fdf4215090f0671af and update document in 37c685ec71bfb9bdef314de2dd6817340867109c, not squash commits but keep commits clean and compact.

Like, if I was you before bf722e59d872ed27735f854df314b06693a0d3d2 has committed, start from 37c685ec71bfb9bdef314de2dd6817340867109c:

First, there is a modification in `sortable-rails-jquery/index.js` at 37c685ec71bfb9bdef314de2dd6817340867109c

``` diff
-//=require ./jquery.bindings.js
+//=require ./jquery.binding.js
```

This change should be done at 1d21dcc06c40a12ed1c7859fdf4215090f0671af, use `git rebase -i` to rewrite commit, since 1d21dcc06c40a12ed1c7859fdf4215090f0671af isn't last commit, so we can't use `git commit --amend`. We fix this first, so later will not happen `both modified` situation and make process simple. Or you can do this in one rebase but you have to deal with conflict. It's quite easy in this case.

```
$ git rebase -i 1d21dcc06c40a12ed1c7859fdf4215090f0671af^

# git brings up editor, in my case is vim.
# change 
pick fa0329d Create index.js
# to 
edit fa0329d Create index.js
# save and quit vim

# then edit index.js from
//=require ./jquery.bindings.js
# to
//=require ./jquery.binding.js
# save and quit vim

$ git add vendor/assets/javascripts/sortable-rails-jquery/index.js

# rewrite commit
$ git commit --amend

# continue rebase
$ git rebase --continue
```

Now you won't see this in `Add jQuery bindings.` commit, it's done in `Create index.js` commit.

``` diff
-//=require ./jquery.bindings.js
+//=require ./jquery.binding.js
```

Do rebase again. This time we rewrite `sortable-rails-jquery/index.js` to include `Sortable.js`, then we use `git commit --amend` rewrite `Add jQuery bindings.` to update document with https://github.com/otaq/sortable-rails/pull/2#issuecomment-241842225 implemented.

Now, we got total 3 commits in this PR, no redundant commits included, in my opinion.

I can do these for you, though.

**Comment by bradlis7** [comment]
Sure, if you want to do that, go ahead.

**Comment by otaq** [comment]
Just released. @bradlis7 Thanks for you contribution!

**Pull request closed without merging**
